name: GitHub Actions Demo along with jhonkings
run-name: Never gonna give you up
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v6
     - uses: actions/setup-python@v2
     - run: echo "Hello world"
     - run: python hello.py
